version: "3.10"

x-settings:
  &global
  environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - task-storage:/data
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    <<: *global


volumes:
  task-storage:
  db-data:
