version: '3.7'

services:
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: quizz
      POSTGRES_PASSWORD: quizz
      POSTGRES_DB: quizz
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg-data:
  redis-data:
