version: "3.10"

x-settings:
  &global
  environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - DATABASE_USER=${DATABASE_USER}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_HOST=${DATABASE_HOST}
    - DATABASE_PORT=${DATABASE_PORT}
    - DATABASE_NAME=${DATABASE_NAME}
    - REDIS_PORT=${REDIS_PORT}
    - REDIS_HOST=${REDIS_HOST}
    - API_PREFIX=${API_PREFIX}
    - SECRET_KEY=${SECRET_KEY}
    - ALGORITHM=${ALGORITHM}

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    <<: *global
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - task-storage:/data
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    <<: *global


volumes:
  task-storage:
  db-data:
